AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  Author: Michael Ludvig <michael.ludvig@enterpriseit.co.nz>
  Description: |-
    Demo of scheduled instance Stop/Start

Parameters:
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet where to launch the EC2 instance

  ImageId:
    Type: String
    Description: AMI ID
    Default: ami-ff4ea59d   # https://aws.amazon.com/amazon-linux-ami/

  StartHourGMT:
    Description: GMT Timezone hour when the Instance will be started.
    Type: Number
    MaxValue: 23
    MinValue: 0
    Default: 17

  StopHourGMT:
    Description: GMT Timezone hour when the Instance will be stopped.
    Type: Number
    MaxValue: 23
    MinValue: 0
    Default: 6

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName

  StartStopRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      Path: /
      Policies:
      - PolicyName: CloudWatchLogsPolicy
        PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
      - PolicyName: StartStopPolicy
        PolicyDocument:
          Statement:
          - Action:
            - ec2:StartInstance
            - ec2:StopInstance
            Effect: Allow
            Resource: '*'

  StartScheduler:
    Type: AWS::Events::Rule
    Properties:
      Description: Instance Start scheduler
      ScheduleExpression: !Sub "cron(0 ${StartHour} ? * * *)"
      Targets:
      - Arn: !GetAtt StartStopLambda.Arn
        Id: StartStopLambda_Target

  StopScheduler:
    Type: AWS::Events::Rule
    Properties:
      Description: Instance Stop scheduler
      ScheduleExpression: !Sub "cron(0 ${StartHour} ? * * *)"
      Targets:
      - Arn: !GetAtt StartStopLambda.Arn
        Id: StartStopLambda_Target

  StartStopSchedulerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StartStopLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StartStopScheduler.Arn

  StartStopLambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          instance_id: !Ref Instance
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt StartStopRole.Arn
      Runtime: python3
      Timeout: 10
      Code:
        ZipFile:
          Fn::Join:
          - '

            '
          - - ""
            - "%%{ec2-start-stop.lambda.py}%%"
