---

AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  Author: Michael Ludvig @ aws.nz
  Description: |-
    Demo of scheduled EC2 instance Stop/Start using
    Lambda function and CloudWatch Events scheduler

Parameters:
  InstanceId:
    Type: AWS::EC2::Instance::Id
    Description: Existing instance ID

  StartCronExpression:
    Description: Cron-like expression when the Instance will be started (UTC Timezone!)
    Type: String
    Default: "0 17 ? * * *"

  StopCronExpression:
    Description: Cron-like expression when the Instance will be stopped (UTC Timezone!)
    Type: String
    Default: "0 6 ? * * *"

Resources:
  StartStopRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      Path: /
      Policies:
      - PolicyName: CloudWatchLogsPolicy
        PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
      - PolicyName: StartStopPolicy
        PolicyDocument:
          Statement:
          - Action:
            - ec2:StartInstances
            - ec2:StopInstances
            Effect: Allow
            Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${InstanceId}'

  StartScheduler:
    Type: AWS::Events::Rule
    Properties:
      Description: Instance Start scheduler
      ScheduleExpression: !Sub "cron(${StartCronExpression})"
      Targets:
      - Arn: !GetAtt StartStopLambda.Arn
        Id: StartStopLambda_Target
        Input: !Sub '{ "instance_id": "${InstanceId}", "action": "start" }'

  StartSchedulerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StartStopLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StartScheduler.Arn

  StopScheduler:
    Type: AWS::Events::Rule
    Properties:
      Description: Instance Stop scheduler
      ScheduleExpression: !Sub "cron(${StopCronExpression})"
      Targets:
      - Arn: !GetAtt StartStopLambda.Arn
        Id: StartStopLambda_Target
        Input: !Sub '{ "instance_id": "${InstanceId}", "action": "stop" }'

  StopSchedulerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StartStopLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StopScheduler.Arn

  StartStopLambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          instance_id: !Ref InstanceId
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt StartStopRole.Arn
      Runtime: python3.6
      Timeout: 10
      Code:
        ZipFile:
          Fn::Join:
          - '

            '
          -
            - "%%{ec2-start-stop.lambda.py}%%"
